### ISSUE TITLE
CP: Update badge on up to date site

### ISSUE THREAD

**Issue by marcorieser** [statamic/cms#10277]
### Bug description

Sometimes the changelog for an addon does not get updated which causes an update badge in cp even if everything is up to date. In my case it's the Translation Manager addon. But found an issue that seems like to underline my case: https://github.com/statamic/cms/issues/6718

<img width="943" alt="Bildschirmfoto_2024-06-07_um_14 11 55" src="https://github.com/statamic/cms/assets/2395800/f96a09fd-8df0-4900-8364-c64e80d6b549">

### How to reproduce

No idea but installing the Translation Manager addon probably reproduces the issue atm.

### Environment

```yaml
Environment
Application Name: Wizard Live
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: statamic-wizard-promotions.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Livewire
Livewire: v3.5.0

Statamic
Addons: 5
Sites: 2 (German, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.4.0
marcorieser/statamic-vitals: 1.2.0
marcorieser/tailwind-merge-statamic: 1.1.0
ryanmitchell/statamic-translation-manager: 2.0.0
stillat/relationships: 2.2.0
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by marcorieser** [comment]
Just noticed that the version on statamic.com is outdated for the addon (1.6.0 instead of 2.0.0): https://statamic.com/addons/thoughtco/translation-manager

**Comment by marcorieser** [comment]
According to Rob, releasing a new version of the addon fixes the issue. Probably because that re-pings (or something) the version update and Statamic can pick it up.

**Comment by robdekort** [comment]
> According to Rob, releasing a new version of the addon fixes the issue. Probably because that re-pings (or something) the version update and Statamic can pick it up.

That's true. Perhaps a resave of the addon on statamic.com might also trigger something. Not sure how stuff works, but perhaps it's an issue on statamic.com and not the CMS.

**Comment by duncanmcclean** [comment]
We've just deployed a fix to Statamic.com which should *hopefully* prevent this issue from happening in future. 

For addons affected by this issue, the addon developer should be able to trigger a re-sync of the product on Statamic.com by resaving their latest release (just edit and re-save, no actual changes are required). 

After that, the product's information should be up-to-date within a minute or two.

**Comment by robdekort** [comment]
Nice. And that’s good to know. I’ll keep an eye out.

**Comment by marcorieser** [comment]
🐐

**Comment by robdekort** [comment]
Notice I'm still seeing this in the latest version. You can see Statamic believes Forma isn't up2date. 

<img width="1346" alt="Screenshot 2024-07-02 at 09 55 43" src="https://github.com/statamic/cms/assets/69107412/f323802c-4f45-47c6-b5d9-9822508b239f">

**Comment by marcorieser** [comment]
> Notice I'm still seeing this in the latest version. You can see Statamic believes Forma isn't up2date.
> 
> <img alt="Screenshot 2024-07-02 at 09 55 43" width="1346" src="https://private-user-images.githubusercontent.com/69107412/344929888-f323802c-4f45-47c6-b5d9-9822508b239f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDczNjEsIm5iZiI6MTcxOTkwNzA2MSwicGF0aCI6Ii82OTEwNzQxMi8zNDQ5Mjk4ODgtZjMyMzgwMmMtNGY0NS00N2M2LWI1ZDktOTgyMjUwOGIyMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA3NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZmU2YjI3NWNjNTZjOGI4OGQyY2Q1ZTg3M2IxNjk5NDYzZGQyODcyNDJhZDcwODRmNmRiOGFkYmI2M2U1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1BgfwZ2lrXNeQmusDNw7Z9UMzh8jdxIdNiVj67DSM6M">

Has the dev of Forma re-triggered the sync as Duncan mentioned above?

**Comment by robdekort** [comment]
> Has the dev of Forma re-triggered the sync as Duncan mentioned above?

I don't know, I'm not @edalzell. But I think the fix doesn't work:

> We've just deployed a fix to Statamic.com which should hopefully prevent this issue from happening in future.

**Comment by robdekort** [comment]
Ah, the latest release from Forma was before the fix. Gotcha.

@edalzell: would you trigger a save on statamic.com like this: "For addons affected by this issue, the addon developer should be able to trigger a re-sync of the product on Statamic.com by resaving their latest release (just edit and re-save, no actual changes are required)."

**Comment by edalzell** [comment]
> @edalzell: would you trigger a save on statamic.com like this: "For addons affected by this issue, the addon developer should be able to trigger a re-sync of the product on Statamic.com by resaving their latest release (just edit and re-save, no actual changes are required)."

Done.

**Comment by robdekort** [comment]
Thanks Erin. 

Unfortunately this issue doesn’t seem solved then. 
![IMG_1388](https://github.com/statamic/cms/assets/69107412/a90b0f86-ad45-46c1-ace6-e6fb3e5050d8)
![IMG_1389](https://github.com/statamic/cms/assets/69107412/7b5a45a7-2546-4052-8bbd-a2d0c915542e)

**Comment by robdekort** [comment]
I cleared the caches btw.

**Comment by duncanmcclean** [comment]
Thanks! We'll need to take another look.

**Comment by robdekort** [comment]
<img width="1264" alt="Screenshot 2024-07-06 at 11 38 07" src="https://github.com/statamic/cms/assets/69107412/1c6b0637-0dd2-47cb-860f-a7d1f07e19d2">
 It seems to be getting a bit worse even 😬

**Comment by robdekort** [comment]
Even weirder, I just updated Statamic Peak SEO to 8.15.3, and the badge increases again. This is not good for my badge OCD ;-).
<img width="1447" alt="Screenshot 2024-07-06 at 15 22 01" src="https://github.com/statamic/cms/assets/69107412/02c514a6-08e7-4a0a-9a5f-a0303e8a4fb2">

**Comment by robdekort** [comment]
Just found out if you run `statamic new badge-galore studio1902/statamic-peak` you can reproduce a fresh straight up lying in your face update badge. It thinks the Tools and Commands addons are out of date.

**Comment by robdekort** [comment]
This is driving me bonkers so I did something that seem to have helped. For the two troubled addons I did the following to get rid of the badges:

1. Tagged and released a new version
2. Ran `composer update`
3. Pulled the releases on github
4. Trashed the tags using `git push --delete origin vX.X.X`
5. Trashed the releases on packagist.org
6. Ran `composer update`

**Comment by robdekort** [comment]
Editing a faulty release on github.com seems to trigger something as well. Then updating the page on statamic.com fixed stuff.

**Comment by duncanmcclean** [comment]
After some troubleshooting, it seems like GitHub isn't sending webhooks when releases are tagged, which is leading Statamic.com to be out-of-date, which subsequently causes the badge in the CP even when you're on the latest version.

I've submitted a support ticket with GitHub. Hopefully they'll have some ideas. 😄

**Comment by duncanmcclean** [comment]
We've just deployed some changes to Statamic.com, which should (hopefully 🤞) prevent this issue from happening in the future.




We've just deployed some changes to Statamic.com, which should (hopefully) prevent this issue from happening in the future.





We've just deployed some changes to Statamic.com, which should hopefully fix this issue.



We've just deployed a fix to Statamic.com which should hopefully prevent this issue from happening in future.

For addons affected by this issue, the addon developer should be able to trigger a re-sync of the product on Statamic.com by resaving their latest release (just edit and re-save, no actual changes are required).

After that, the product's information should be up-to-date within a minute or two.

**Comment by duncanmcclean** [comment]
We've just deployed some changes to Statamic.com, which should (_hopefully_ 🤞) prevent this issue from happening in the future.

For addons where the latest release isn't showing, the addon developer can trigger a sync by re-saving their product on the Marketplace. Within a few minutes, the product's information (including releases) should be up-to-date.

**Comment by robdekort** [comment]
Oh Duncan you wonderful man! I just tested on a few sites and it seems all good now. Might be able to tick this one off.

**Comment by duncanmcclean** [comment]
Great! 

I'm going to close this issue now. If anyone's still seeing the update badge when it shouldn't be showing...

* If the addon's latest release was tagged *before* we deployed our fix yesterday, the addon developer will need to re-save their addon on the Marketplace in order to force Statamic.com to sync with GitHub. 
* If the addon's latest release was tagged *after* we deployed our fix yesterday, it probably means the issue is back 😞. In which case, please leave a comment on this issue and we can take a look.

**Comment by robdekort** [comment]
> If the addon's latest release was tagged after we deployed our fix yesterday, it probably means the issue is back 😞. In which case, please leave a comment on this issue and we can take a look.

Afraid to inform ya that this issue is still a thing.

**Comment by duncanmcclean** [comment]
Dang it!

**Comment by efc** [comment]
This is still a thing. I am seeing the problem on Static Site Generator 3.0.2 which is currently the latest update, but does not match the 3.0.1 version that Statamic seems to think is current. 

I wonder if Statamic could have some sort of "sanity check" on the versions before it shows the update badge so that it can recognize 3.0.2 > 3.0.1 even if statamic.com does not know 3.0.2 exists? Maybe this could trigger some sort of "caution" symbol in the updates list but not a full-on red badge in the Statamic sidebar (which seems to be what really annoys people)?

**Comment by duncanmcclean** [comment]
> This is still a thing. I am seeing the problem on Static Site Generator 3.0.2 which is currently the latest update, but does not match the 3.0.1 version that Statamic seems to think is current.

Yep, we haven't had time to look at this again but it's on our list. I've purged the cache for the SSG addon on statamic.com, so it should hopefully be fixed now.

> I wonder if Statamic could have some sort of "sanity check" on the versions before it shows the update badge so that it can recognize 3.0.2 > 3.0.1 even if statamic.com does not know 3.0.2 exists? Maybe this could trigger some sort of "caution" symbol in the updates list but not a full-on red badge in the Statamic sidebar (which seems to be what really annoys people)?

We could certainly look at doing that.

**Comment by iLord-DEV** [comment]
Still seeing this in Statamic 6.7.1 with statamic/ssg. CP shows 4.0.0 as 'Update available' while 4.1.0 is installed. Notably, `composer require statamic/ssg:4.0.0` isn't even installable (fails with 'statamic/cms is the root package and cannot be modified'), yet the updater still suggests it as an upgrade.

**Comment by duncanmcclean** [comment]
@iLord-DEV I've purged the cache for the SSG addon. If you're having issues installing/updating, please open an issue on the `ssg` repo.

**Comment by robdekort** [comment]
Could you do this for Logger for Statamic as well? Running into these badges as well again.

**Comment by duncanmcclean** [comment]
> Could you do this for Logger for Statamic as well? Running into these badges as well again.

Done!

**Comment by robdekort** [comment]
Thanks!

**Comment by iLord-DEV** [comment]
> [@iLord-DEV](https://github.com/iLord-DEV) I've purged the cache for the SSG addon. If you're having issues installing/updating, please open an issue on the `ssg` repo.

Thank you, better. But still it shows Update Count 1 while all packages are up to date.

**Comment by duncanmcclean** [comment]
@iLord-DEV Do you have any other addons installed? Can you show a screenshot of the "Addons" page?

Have you tried clearing the cache with `php artisan cache:clear`?

**Comment by iLord-DEV** [comment]
> [@iLord-DEV](https://github.com/iLord-DEV) Do you have any other addons installed? Can you show a screenshot of the "Addons" page?
> 
> Have you tried clearing the cache with `php artisan cache:clear`?

Yes i did. Different Results. 

Local dev: update count 1 -  but all packages green
Production: update count 0 (!) - but all packages green

**Comment by malle-pietje** [comment]
After upgrading to v6 I am seeing this badge again while all updates all "green", even after `php artisan cache:clear`...

<img width="1572" height="632" alt="Image" src="https://github.com/user-attachments/assets/9e4f2361-844e-4d71-a5b8-dc1760aa6c99" />

**Comment by duncanmcclean** [comment]
@malle-pietje Looks like a few addons had stale data on the Marketplace - I've just purged the cache. Can you try running `php artisan cache:clear` to see if that helps?

Also, you're using 1.2.0 of the "Index Now" addon, but the latest release on GitHub is [v1.1.0](https://github.com/Art-of-WiFi/statamic-indexnow/releases). You might need to create a release for the tag.

**Comment by robdekort** [comment]
This issue starts to pop up regularly again here as well, almost with every addon release.

**Comment by malle-pietje** [comment]
In my case the Logbook add-on appears to be triggering the badge:

<img width="1100" height="385" alt="Image" src="https://github.com/user-attachments/assets/7fe4e392-f013-4382-a3b4-95bd910966b1" />

While I do have version 4.0.0 of the add-on installed.

**Comment by malle-pietje** [comment]
@duncanmcclean Thanks, I ran that artisan command (also cleared all caches through cp) which did clean this view:

<img width="1058" height="365" alt="Image" src="https://github.com/user-attachments/assets/09f1d97a-b877-4176-abdc-8b2ae5c2fb21" />

Unfortunately the badge in the sidebar still remains.

**Comment by helloDanuk** [comment]
I also see an update badge for the "Clear Assets" add-on. Version 3.4.0 is installed but CP and marketplace shows 3.3.0 as the newest version.

**Comment by duncanmcclean** [comment]
@helloDanuk Just purged the cache for the "Clear Assets" addon.

**Comment by marcorieser** [comment]
I agree with @efc. A local check could be handy: https://github.com/statamic/ideas/issues/1457

**Comment by duncanmcclean** [comment]
I've just deployed some fixes to the Marketplace which will _hopefully_ fix this once and for all. 👌

Even if it does happen again, a scheduled job will now catch and fix out-of-date releases automatically. So if an addon's changelog ever falls behind (causing the update badge), it'll fix itself within a day. 

With that in mind, I'm going to close this issue now. If you're still seeing incorrect update badges after a day or so, please let us know and we can dig into this some more.

_FWIW: I've hated this bug as much as everyone else. We've tried a lot of things behind the scenes but none of them stuck. Hopefully this fix + new scheduled job will solve the issue for everyone._
