### ISSUE TITLE
Using a conditional with the yield tag no longer works

### ISSUE THREAD

**Issue by ChanceArthur** [statamic/cms#1193]
I've been using `{{ if {yield:sidebar} }}` in my layout to check whether the template is going to have a sidebar section.
This has worked in v2, and in v3 up to beta-8. On beta-9 I'm now getting `syntax error, unexpected '<'`

**Comment by jackmcdade** [comment]
Ah, thank you for bringing this up! We were fixing a different Antlers parser issue and removed some code that, as it turns out, needed to remain. This was exactly the info we needed to handle both sides. Fixed in 19ba9979!

**Comment by ChanceArthur** [comment]
I can confirm it's working now. Thanks!

**Comment by ChanceArthur** [comment]
Hey @jackmcdade, this broke again in 3.0.9 and is still broken in 3.0.10.

Is this a bug, or should I stop using this method?

Thanks!

**Comment by jasonvarga** [comment]
What's the error, and how are you using the yield tag in your template? Simply adding `{{ if {yield:sidebar} }} test {{ /if }}` to my template doesn't cause any error.

**Comment by ChanceArthur** [comment]
It doesn't call an error. It'll just act as if it and its contents don't exist.

**Comment by ChanceArthur** [comment]
```
{{ if {yield:something} }}
      <div class="container">
          <div class="some-div"></div>

        {{ yield:something }}

      </div>
    {{ /if }}
```

**Comment by jasonvarga** [comment]
Thanks. Unfortunately regressed introduced in 63514c2e61936825fd419a2de057916485b1044e

**Comment by sptv2reg** [comment]
Has this bug been reintroduced (Statamic 3.4.7)?

I've got this code in a show.antlers.html:

```
{{ section:sidebar }}
  <h2>Sidebar: {{ title }}</h2>
{{ /section:sidebar }}
```

And then this code in my layouts.antlers.html:

```
{{ if {yield:sidebar} }}
  // only show if sidebar is present in template
  <aside>
    {{ yield:sidebar }}
  </aside>
{{ /if }}
```
          
But it seems to me that the comment "// only show..." is always rendered no matter if the whole section tag is removed from show.antlers.html.
