### ISSUE TITLE
[6.x] Conditions not behaving correctly

### ISSUE THREAD

**Issue by martyf** [statamic/cms#12835]
### Bug description

When editing a Fieldset or Blueprint, and going to the "Conditions" tab for the field, trying to change "Always show" just makes the select box appear as "Select..." with no options.

Replicated in Firefox and Safari

https://github.com/user-attachments/assets/7a49298c-26e9-4977-9d83-80cee3ac6277

### How to reproduce

1. Install Statamic 6 Alpha 14
2. Edit a Blueprint or create a Fieldset
3. Select a field, go to the Conditions tab
4. Try to change the "Conditions" select box

### Logs

```shell

```

### Environment

```yaml
Statamic 6 Alpha 14
```

### Installation

Fresh statamic/statamic site via CLI

**Comment by duncanmcclean** [comment]
I can't seem to reproduce this. It works fine for me in Safari and Chrome (ignore the wonky styles, that's a different issue).

https://github.com/user-attachments/assets/d3a98faa-a0b4-4313-875c-ae06cab43a65

Do you have any addons installed? Can you provide the full output of `php please support:details`?

**Comment by martyf** [comment]
Replicated with a clean new Statamic 6 install, with zero addons.

Inspecting element in Firefox shows it's a z-index issue. If I butcher it to `z-index: 10000000000 !important` I see it (broken, like in your video). 

This screenshot shows the `data-reka-popper-content-wrapper` element in the tree - but just not high enough in the z stack.

<img width="298" height="300" alt="Image" src="https://github.com/user-attachments/assets/ee1780d5-f6fd-40fc-bb53-b19808e621a0" />

**Comment by duncanmcclean** [comment]
How strange... I've just tried a couple of different sites (on the latest alpha) and I can't see it there either. 🤔 

I don't suppose running `php artisan statamic:install` changes anything, does it?

**Comment by martyf** [comment]
No change... but did _another_ new install and it appears as yours. Very very odd indeed. Maybe something odd from an upgrade process, as the z-index one has been around since alpha 1.

**Comment by duncanmcclean** [comment]
Possibly. I know we've done a couple of z-index fixes recently. 🤷‍♂️

**Comment by duncanmcclean** [comment]
Looks like this was fixed by #12829, which was released as part of [v6.0.0-alpha.15](https://github.com/statamic/cms/releases/tag/v6.0.0-alpha.15). I see the same issue when I revert that PR.

FYI: The dropdown weirdness should be fixed by #13053

**Comment by martyf** [comment]
z-index is looking good, but I'm still seeing the wonky select box though - I assume that's what you mean by #13053? Can create a new issue if you want to keep things separate.

I see it in both Firefox Dev Edition and Safari.

<img width="187" height="247" alt="Image" src="https://github.com/user-attachments/assets/8b4a6bc2-676b-450d-97d6-466cf09b1c6e" />

**Comment by duncanmcclean** [comment]
Yep, the wonky select box will be fixed by https://github.com/statamic/cms/pull/13053.
