### ISSUE TITLE
The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly

### ISSUE THREAD

**Issue by joseph-d** [statamic/cms#3383]
## Bug Description

Upgrading or downgrading Statamic from the cp results in an error due to the `HOME` or `COMPOSER_HOME` env variables not being set.                 
                                                                               
## How to Reproduce

Upgrade or downgrade Statamic from the cp

## Extra Detail

```
In Factory.php line 677:
                                                                               
  The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly     
```                   

## Environment

Statamic: `3.0.46 Solo`
Laravel: `8.32.1`
PHP: `7.4.16`
OS: `Ubuntu 20.04`
Environment: `Laravel Sail / Docker`

No addons installed

**Install method (choose one):**
Fresh install from `statamic/statamic` with `laravel/sail` added afterwards to serve.

## Workarounds

- Running `composer update` from the command line works fine and Statamic is properly upgraded or downgraded.
- Manually hacking the core of `vendor/composer/composer/src/Composer/Factory.php` from `$home = getenv('HOME');` to `$home = '/home/sail';` makes it work properly. I only mention this in case it's of any use. 

## Other notes

- If I do `artisan tinker` and then run `dd(_$ENV);` I can see that there is a `HOME` variable specifically set to `/home/sail` which is what it should be (and which is what makes it work as per the workaround above) but if I insert the same `dd($_ENV)` into the `Factory.php` file then the `HOME` env var is no longer present.
- I have tried adding both `HOME='/home/sail'` and `COMPOSER_HOME='/home/sail` to my `.env` and it doesn't make any difference
- Laravel Sail uses Laravel's own `artisan serve` to serve the application rather than nginx/apache. However, I don't believe that this is related to the error as I already spoke to someone on Discord who's running a regular Ubuntu 20.04 setup (ie: no Sail or Docker) and experiencing the same issue.

**Comment by duncanmcclean** [comment]
I've never used Laravel Sail myself so it might be a good idea to search for any open/closed issues on the laravel/sail repository to see if anyone has come across the same issue as you.

However, as this is an error from Composer, relating to your local setup and not Statamic, I'm going to close this issue.

**Comment by Jars-of-jam-Scheduler** [comment]
Hi everyone,

This bug is probably not bound to Laravel Sail. I experience it too but don't have Laravel Sail nor Docker.
I've installed Laravel locally by using Composer (`composer global require laravel/installer ; laravel new example-app`). 

Bug description: same than the OP.
How to reproduce: idem.
Extra detail: idem.
Environment:
- Statamic: 3.0.46 Solo (this bug occurred with previous versions too)
- Laravel Framework: 8.32.1 (perhaps this bug occurred with previous versions too)
- PHP: 8.0.3 (this bug occurred with previous versions too) (NB: so it's a different version than the OP)
- OS: Ubuntu 20.04.2 LTS
- Environment: Composer only (NB: so it's a different environment than the OP, I don't use Docker & Laravel Sail)
- No addons installed
Install method (choose one): don't remember, I probably followed the docs (probability: 99%...)
Workarounds: idem (however I didn't test to change the code of `vendor/composer/composer/src/Composer/Factory.php`)
Other notes: I am the one the author mentions in his last sentence :D (no other notes to say)

**Comment by duncanmcclean** [comment]
@jasonvarga What are your thoughts on re-opening this issue? I'm not too sure it's actually a Statamic issue but one to do with how Composer is setup.

**Comment by joseph-d** [comment]
The main thing that makes me wonder whether it's a Statamic issue or not is the fact that the `HOME` env var is present and correct from the `tinker` console but them somehow disappears if I `dd` it throughout various stages of the Statamic and Composer packages. However, I admit that I don't understand enough about the inner workings to know whether or not this is normal.

That said, I'm happy to participate in any way I can to help to resolve this issue if you do think there's a chance it is Statamic related.

I defer to your judgement!

**Comment by duncanmcclean** [comment]
I'm just having a look into this issue now, here's some findings. 

Looks like the exception `The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly` is [thrown by Composer itself](https://github.com/composer/composer/blob/master/src/Composer/Factory.php#L677).

It happens after it can't see any home directory set, using the `getenv('HOME')` PHP function, which I believe tries to retrieve system environment variables (not the same thing as your project `.env` file).

@joseph-d You said that you tried doing `getenv('HOME')` in Tinker which worked but didn't if you tried inside Statamic? How were you running Tinker, locally or inside Sail's docker container?

**Comment by joseph-d** [comment]
@duncanmcclean I was running Tinker from inside Sail's docker container. Here's my output:

```
joseph-d@vulcan:~/docker/project1$ sail artisan tinker
Psy Shell v0.10.7 (PHP 7.4.16 — cli) by Justin Hileman
>>> getenv('HOME') 
=> "/home/sail"
>>> 
```
If I run `sail composer update` from the command line then the Statamic update works.

In case it's useful, here's the full output of `getenv()`:

```
joseph-d@vulcan:~/docker/project1$ sail artisan tinker
Psy Shell v0.10.7 (PHP 7.4.16 — cli) by Justin Hileman
>>> getenv();
=> [
     "PATH" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
     "HOSTNAME" => "f1ff77bf7253",
     "TERM" => "xterm",
     "WWWUSER" => "1000",
     "LARAVEL_SAIL" => "1",
     "DEBIAN_FRONTEND" => "noninteractive",
     "TZ" => "UTC",
     "HOME" => "/home/sail",
     "SHELL_VERBOSITY" => "0",
     "LINES" => "22",
     "COLUMNS" => "260",
   ]
```

As the error is coming from Line 677 of `composer/composer/src/Composer/Factory.php` I put a `dd(getenv())` in there to see what would happen and I get this in the composer modal that pops up in the CP for the update:

```
]8;;file:///var/www/html/vendor/composer/composer/src/Composer/Factory.php#L677\^]8;;\ array:6 [
  "LARAVEL_SAIL" => "1"
  "PWD" => "/var/www/html"
  "COMPOSER_BINARY" => "/var/www/html/vendor/composer/composer/bin/composer"
  "LINES" => "50"
  "COLUMNS" => "80"
  "SHELL_VERBOSITY" => "0"
]
```

Not that I particularly know what I'm doing, but I also put a `dd(getenv()` in the `install` method of `Statamic\Http\Controllers\CP\Updater\UpdateProductController` and then the output is just:

```
array:2 [▼
  "LARAVEL_SAIL" => "1"
  "PWD" => "/var/www/html/public"
]
```

Please note that I'm getting this from the network tab in the browser dev tools, *not* the modal that pops up with composer output which doesn't seem to be affected by the `dd`.

Let me know if you need any other info!

**Comment by michaelr0** [comment]
I've been able to get this to progress slightly further.

In my particular case I'm running locally via php artisan serve (using php8.0 from homebrew)
And am trying to run a Statamic update via the CP Gui

If you use the database (and probably any other driver that isn't sync) queue driver then it gets past the error.
```
In Factory.php line 677:
                                                                               
  The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly 
``` 

This however when you try to run the queue, as it seems to delete Statamic prior to updating it, which then causes the application and queue to fall over.


I tried tracing it like the above comment with dd() and it seems that that the HOME ENV is set up until when SymfonyProcess is called around line 272/273 in Statamic\Console\Processes\Process.php

I had a look at the documentation for Symfony Process and I was able to get the sync driver progressing as far as the database one did, by passing the ENV to the Symfony Process by changing line 272/273 in Statamic\Console\Processes\Process.php.

From:
```php
  ? SymfonyProcess::fromShellCommandline($command, $path ?? $this->basePath)
  : new SymfonyProcess($command, $path ?? $this->basePath);
```

To:

```php
  ? SymfonyProcess::fromShellCommandline($command, $path ?? $this->basePath, getenv())
  : new SymfonyProcess($command, $path ?? $this->basePath, getenv());
```

However as noted with the database driver, this appears to fall over once it removes Statamic.

**Comment by michaelr0** [comment]
In addition to the above, it seems like this also impacts installing addons. 
The changes I listed above seems to get installations working.

**Comment by michaelr0** [comment]
This should be resolved soon when it is tagged and released as the following has been accepted via PR.

```php
    ? SymfonyProcess::fromShellCommandline($command, $path ?? $this->basePath, ['HOME' => getenv('HOME)])
    : new SymfonyProcess($command, $path ?? $this->basePath, ['HOME' => getenv('HOME)]);
```

However until you have the newer version, you still won't be able to run the update from the control panel, you'll need to do it via composer update.

**Comment by michapixel** [comment]
After changing the above lines/line it updates in my environment but satill getting errors afterwards:
"Malformed UTF-8 characters, possibly incorrectly encoded"

Might be a path thing since i'm on windows and those almost always get in the way.

**Comment by michapixel** [comment]
and the error comes up when the ajax polls after the update but when when composer does it's thing 
"Generating optimized autoload files".

**Comment by michaelr0** [comment]
> After changing the above lines/line it updates in my environment but satill getting errors afterwards:
> "Malformed UTF-8 characters, possibly incorrectly encoded"
> 
> Might be a path thing since i'm on windows and those almost always get in the way.

Was this during a Statamic update? Can you implement the "fix" again and see if you can install/remove/update add-ons?

**Comment by michapixel** [comment]
Yes, this was during a Statamic update. I changed the lines you proposed and at least it updated afterwards. 
I'm now trying to revert the update to see where it fails at the end. 
I had an update for a plugin which also installed fine but errored in the end. 


I did the same to my current project staging-server, but that's a limited/special server (ionos/1&1) where i can only update via ssh. There's no composer installed and i couldn't find a way "tell" the 'updater/installer' the path to the composer.phar ... and there's another problem there, that it's not just "php /path_to/composer.phar", the server has four or five versions of php installed, so i'd need a way to tell statamic the correct way to call php, right? I guess this is out of scope for statamic, but these servers are not that rare in europe, at least when you have one from 1&1/IONOS. 


Sorry to ask, but are you an official maintainer? 
I wondered why there are so many and frequent updates, yet the updater is ... well it seems it needs more testing .)

**Comment by michapixel** [comment]
So i just tested the updater for a plugin (Logbook that is)
and it succeeded (with your patch) but fails to finish:

Uncaught (in promise) Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:62
createError.js:16:14

So i looked into the statamic logfile:

[2021-05-25 07:25:11] production.ERROR: Composer Process: 
[33mIn WindowsPipes.php line 63:[39m
[37;41m                                                                                                                       [39;49m
[37;41m  A temporary file could not be opened to write the process output: fopen(C:\Windows\sf_proc_00.out.lock): Failed to   [39;49m
[37;41m  open stream: Permission denied                                                                                       [39;49m
[37;41m                                                                                                                       [39;49m

and later on:

[2021-05-25 07:25:11] production.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":"64a1beb0-7096-4aa1-93a7-83ea13bc86ed","exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at D:\
epositories\\gitlab\
ova-diverse\\eichnerbau_cms\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php:84)
[stacktrace]


Remember: this is only th GUI/Web-Updater, the console update works just fine.

**Comment by michapixel** [comment]
![firefox_XhUcrL3Y8j](https://user-images.githubusercontent.com/370877/119615613-e159c900-bdff-11eb-9f0d-4eb19f13c2ba.png)

![sublime_text_wTMbXdfW0K](https://user-images.githubusercontent.com/370877/119615636-e74faa00-bdff-11eb-84ef-281d6e0563ed.png)

**Comment by michapixel** [comment]
The Malformed UTF8 thing comes after updating via Web, when the GUI polls e.g.:
https://eichner-bau.test/cms/composer/check?package=aryehraber%2Fstatamic-logbook

This check results in a 500 / an answer / dump:

XHR
GET
https://eichner-bau.test/cms/composer/check?package=aryehraber%2Fstatamic-logbook
[HTTP/1.1 500 Internal Server Error 171ms]

	
message	"Malformed UTF-8 characters, possibly incorrectly encoded"
exception	"InvalidArgumentException"
file	"D:\\repositories\\gitlab\\nova-diverse\\eichnerbau_cms\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php"
line	84
trace	[ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
0	Object { file: "D:\\repositories\\gitlab\\nova-diverse\\eichnerbau_cms\\vendor\\symfony\\http-foundation\\JsonResponse.php", line: 54, function: "setData", … }
1	Object { file: "D:\\repositories\\gitlab\\nova-diverse\\eichnerbau_cms\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\JsonResponse.php", line: 32, function: "__construct", … }


And so on.

**Comment by michapixel** [comment]
Oh, BTW: there's no uninstall-nutton/link in the CP for addons under updates ... you have to go through /addons which is ... weird.

**Comment by michapixel** [comment]
Uninstall-process is broken in the CP:
raises a 500:

production.ERROR: Trying to get property 'installed' of non-object {"userId":"64a1beb0-7096-4aa1-93a7-83ea13bc86ed","exception":"[object] (ErrorException(code: 0): Trying to get property 'installed' of non-object at D:\
epositories\\gitlab\
ova-diverse\\eichnerbau_cms\\vendor\\statamic\\cms\\src\\Console\\Processes\\Composer.php:36)
[stacktrace]
[....]

**Comment by michaelr0** [comment]
Hi Michapixel,

I'm not one of the maintainers, actually I'm new to Statamic, but had the initial issue on Mac OS and Ubuntu and was able to find a solution that worked for me.

I'm unable to test/replicate your issue as I don't have any Windows installations to test with.

As for the issue regarding permissions and sf_proc_00.out.lock, I'd suggest to check what tmp directory you have configured in your php/webserver settings, as I think that might be where C:\Windows is coming from, but I assume that it shouldn't be using that directory for temporary storage.

Could you also try with a new statamic install, just to isolate any changes or packages that are project specific for you?

Thanks.

**Comment by jasonvarga** [comment]
Please open a separate issue if you're experiencing a different error to what's described here.

This issue is about `The HOME or COMPOSER_HOME environment variable must be set for composer to  run correctly` and should be fixed in the next release.

**Comment by netwrkx** [comment]
@jasonvarga do you have any idea if `The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly` issue has been fixed

**Comment by jasonvarga** [comment]
I believe it has, in #3734 which made it into 3.1.17

**Comment by joseph-d** [comment]
The issue -- as described when I opened this issue -- still appears to be present as recently as 3.1.24

**Comment by michaelr0** [comment]
For anyone still having this issue, can you advise what OS/Platform you are on and what method you are using to 'serve' your application (artisan serve, sail, vagrant etc...)

Also, can you try updating the `protected function newSymfonyProcess($command, $path = null)` function in `Statamic\Console\Processes\Process.php` to the following.

```php
    /**
     * New symfony process.
     *
     * @param string $command
     * @param string|null $path
     * @return SymfonyProcess
     */
    protected function newSymfonyProcess($command, $path = null)
    {
        // Ensure command is either an array or string.
        if (! is_array($command)) {
            $command = (string) $command;
        }

        $composerEnv = [
            'HOME' => getenv('HOME'),
            // 'COMPOSER_HOME' => getenv('COMPOSER_HOME'),
            // 'COMPOSER_CACHE_DIR' => getenv('COMPOSER_CACHE_DIR'),
            // 'COMPOSER_AUTH' => getenv('COMPOSER_AUTH'),
            // 'USERPROFILE' => getenv('USERPROFILE'),
        ];

        // if (Platform::isWindows()) {
        //     $composerEnv['APPDATA'] = getenv('APPDATA');
        //     $composerEnv['LOCALAPPDATA'] = getenv('LOCALAPPDATA');
        // }

        // Handle both string and array command formats.
        $process = is_string($command) && method_exists(SymfonyProcess::class, 'fromShellCommandLine')
            ? SymfonyProcess::fromShellCommandline($command, $path ?? $this->basePath, $composerEnv)
            : new SymfonyProcess($command, $path ?? $this->basePath, $composerEnv);

        $process->setTimeout(null);

        return $process;
    }
```

And repeat the upgrade, if it fails then try uncommenting various parts of `$composerEnv` and or the `Platform::isWindows` section if that applies to you, then try upgrading again. 
In between upgrade attempts, ensure that the function hasn't been replaced with the original from Statamic.

Then if any of those work for you, post them back in here so they can be put into https://github.com/statamic/cms/pull/4027)

**Comment by joseph-d** [comment]
Hello @michaelr0 thank you for your work with this.

I can confirm that I am still getting the same error that I originally specified when I opened this issue.

I am now on Statamic 3.1.28, Ubuntu 20.04, Laravel Sail (PHP 8 runtime). I have tried pasting the function that you gave above into the relevant place and also uncommented the `$composerEnv` lines (both all at once then one at a time) but the issue remains.

Please let me know if you need any other details or if there is anything else I can test.

**Comment by michaelr0** [comment]
> Hello @michaelr0 thank you for your work with this.
> 
> I can confirm that I am still getting the same error that I originally specified when I opened this issue.
> 
> I am now on Statamic 3.1.28, Ubuntu 20.04, Laravel Sail (PHP 8 runtime). I have tried pasting the function that you gave above into the relevant place and also uncommented the `$composerEnv` lines (both all at once then one at a time) but the issue remains.
> 
> Please let me know if you need any other details or if there is anything else I can test.

Not a problem, hmm let's try going all in. Can you set `composerEnv` to `$composerEnv = getenv();`

Thanks for the info btw, I'll see if I can also replicate it.

**Comment by michaelr0** [comment]
@joseph-d I think I've had further success with this now, can you try this in your `Statamic\Console\Processes\Process`

```php
<?php

namespace Statamic\Console\Processes;

use Closure;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Statamic\Support\Arr;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\PhpExecutableFinder;
use Symfony\Component\Process\Process as SymfonyProcess;

class Process
{
    const CACHE_EXPIRY_MINUTES = 10;

    /**
     * @var string
     */
    protected $basePath;

    /**
     * @var string
     */
    protected $output;

    /**
     * @var bool
     */
    protected $colorized = false;

    /**
     * @var array
     */
    protected $errorOutput = [];

    /**
     * @var bool
     */
    protected $logErrorOutput = true;

    /**
     * @var array
     */
    protected $env = [];

    /**
     * Create new process on path.
     *
     * @param string|null $basePath
     */
    public function __construct($basePath = null)
    {
        $this->basePath = str_finish($basePath ?? base_path(), '/');

        $this->constructEnv();
    }

    /**
     * Construct the environment variables that will be passed to the process.
     *
     * @return void
     */
    protected function constructEnv()
    {
        $filteredEnv = array_merge([
            'HOME',
            'LARAVEL_SAIL',
        ], config('statamic.system.system_environment_variables', []));

        $this->env = collect(getenv())
            ->only($filteredEnv)
            ->toArray();

        if ($this->isRunningInSail() && ! isset($this->env['HOME'])) {
            $this->env['HOME'] = '/home/sail';
        }
    }

    /**
     * Check to see if Statamic is running in Laravel Sail.
     *
     * @return bool
     */
    protected function isRunningInSail(): bool
    {
        return isset($this->env['LARAVEL_SAIL']) && $this->env['LARAVEL_SAIL'] === '1';
    }

    /**
     * Create new process on path.
     *
     * @param string|null $basePath
     * @return static
     */
    public static function create($basePath = null)
    {
        return new static($basePath);
    }

    /**
     * Run the command.
     *
     * @param string|array $command
     * @param string|null $cacheKey
     * @return mixed
     * @throws ProcessFailedException
     */
    public function run($command, $cacheKey = null)
    {
        $process = $this->newSymfonyProcess($command, $this->basePath);

        $this->errorOutput = [];

        if ($cacheKey) {
            $this->runAndCacheOutput($process, $cacheKey);

            return;
        }

        return $this->runAndReturnOutput($process);
    }

    /**
     * Run and externally operate on ouput.
     *
     * @param mixed $command
     * @param mixed $operateOnOutput
     * @return string
     */
    public function runAndOperateOnOutput($command, $operateOnOutput)
    {
        $process = $this->newSymfonyProcess($command, $this->basePath);

        $this->errorOutput = [];

        $this->output = null;

        $process->run(function ($type, $buffer) use (&$output, $operateOnOutput) {
            $this->logErrorOutput($type, $buffer);
            $this->output .= $operateOnOutput($buffer);
        }, $this->env);

        return $this->output;
    }

    /**
     * Check if process has error output.
     *
     * @return bool
     */
    public function hasErrorOutput()
    {
        return (bool) $this->errorOutput;
    }

    /**
     * Run callback without logging errors.
     *
     * @param Closure $callable
     * @return mixed
     */
    public function withoutLoggingErrors(Closure $callback)
    {
        $this->logErrorOutput = false;

        $output = $callback($this);

        $this->logErrorOutput = true;

        return $output;
    }

    /**
     * Run and return output when finished.
     *
     * @param SymfonyProcess $process
     * @return string
     */
    private function runAndReturnOutput($process)
    {
        $this->output = null;

        $process->run(function ($type, $buffer) use (&$output) {
            $this->logErrorOutput($type, $buffer);
            $this->output .= $buffer;
        }, $this->env);

        return $this->normalizeOutput($this->output);
    }

    /**
     * Run and append output to cache as it's generated.
     *
     * @param SymfonyProcess $process
     * @param string $cacheKey
     */
    private function runAndCacheOutput($process, $cacheKey)
    {
        $this->output = null;

        Cache::forget($cacheKey);

        $this->appendOutputToCache($cacheKey, null);

        $process->run(function ($type, $buffer) use ($cacheKey) {
            $this->logErrorOutput($type, $buffer);
            $this->appendOutputToCache($cacheKey, $buffer);
        }, $this->env);

        $this->setCompletedOnCache($cacheKey);
    }

    /**
     * Log error (stderr) output.
     *
     * @param string $type
     * @param string $buffer
     */
    private function logErrorOutput($type, $buffer)
    {
        if ($type !== 'err') {
            return;
        }

        $this->errorOutput[] = $buffer;

        if (! $this->logErrorOutput) {
            return;
        }

        $process = (new \ReflectionClass($this))->getShortName();

        Log::error("{$process} Process: {$buffer}");
    }

    /**
     * Append output to cache.
     *
     * @param string $cacheKey
     * @param string $output
     */
    private function appendOutputToCache($cacheKey, $output)
    {
        Cache::put($cacheKey, [
            'completed' => false,
            'output' => $this->output .= $output,
        ], now()->addMinutes(self::CACHE_EXPIRY_MINUTES));
    }

    /**
     * Set completed on cache.
     *
     * @param string $cacheKey
     */
    private function setCompletedOnCache($cacheKey)
    {
        Cache::put($cacheKey, [
            'completed' => true,
            'output' => $this->output,
        ], now()->addMinutes(self::CACHE_EXPIRY_MINUTES));
    }

    /**
     * Get cached output.
     *
     * @param string $cacheKey
     * @return array
     */
    public function cachedOutput(string $cacheKey)
    {
        $cache = Cache::get($cacheKey) ?? ['output' => false];

        $cache['output'] = $this->normalizeOutput($cache['output']);

        return $cache;
    }

    /**
     * Get cached output for last completed process.
     *
     * @param string $cacheKey
     * @return array
     */
    public function lastCompletedCachedOutput(string $cacheKey)
    {
        $cache = $this->cachedOutput($cacheKey);

        return Arr::get($cache, 'completed') ? $cache : ['output' => false];
    }

    /**
     * Absolute path to PHP Binary.
     *
     * @return string
     */
    public function phpBinary()
    {
        return (new PhpExecutableFinder)->find();
    }

    /**
     * Crank parent process up to eleven (doesn't apply to child process called by run method).
     */
    public function toEleven()
    {
        @ini_set('memory_limit', config('statamic.system.php_memory_limit'));

        @set_time_limit(config('statamic.system.php_max_execution_time'));
    }

    public function colorized()
    {
        $this->colorized = true;

        return $this;
    }

    /**
     * Normalize output.
     *
     * @param mixed $output
     * @return mixed
     */
    public function normalizeOutput($output)
    {
        if (is_null($output)) {
            return $output;
        }

        // Remove terminal color codes.
        if (! $this->colorized) {
            $output = preg_replace('/\\e\[[0-9]+m/', '', $output);
        }

        // Remove trailing new line.
        $output = preg_replace('/\\n$/', '', $output);

        return $output;
    }

    /**
     * New symfony process.
     *
     * @param string $command
     * @param string|null $path
     * @return SymfonyProcess
     */
    protected function newSymfonyProcess($command, $path = null)
    {
        // Ensure command is either an array or string.
        if (! is_array($command)) {
            $command = (string) $command;
        }

        // Handle both string and array command formats.
        $process = is_string($command) && method_exists(SymfonyProcess::class, 'fromShellCommandLine')
            ? SymfonyProcess::fromShellCommandline($command, $path ?? $this->basePath, $this->env)
            : new SymfonyProcess($command, $path ?? $this->basePath, $this->env);

        $process->setTimeout(null);

        return $process;
    }
}
```

**Comment by joseph-d** [comment]
Hi @michaelr0 - I can confirm that this works on my Ubuntu / Sail setup! 

Just to confirm, though, I copied and pasted the entire chunk of PHP that you originally posted (because I saw that as an email notification from github before I looked at the actual issue) but it looks like you re-posted a set of instructions about which specific functions to change since then. So the test I just did was literally replacing the entire class that you sent earlier.

Please let me know if you'd like me to test anything else.

**Comment by michaelr0** [comment]
> Hi @michaelr0 - I can confirm that this works on my Ubuntu / Sail setup!
> 
> Just to confirm, though, I copied and pasted the entire chunk of PHP that you originally posted (because I saw that as an email notification from github before I looked at the actual issue) but it looks like you re-posted a set of instructions about which specific functions to change since then. So the test I just did was literally replacing the entire class that you sent earlier.
> 
> Please let me know if you'd like me to test anything else.

Hi @joseph-d,

That's awesome news!
Perhaps just give it a quick test and make sure that you can install/remove and update addons as well, as I know the issue also impacts that functionality.

Indeed I did originally post the entire file, then decided to split it up, functionally it should be exactly the same, so other than the above test with addons, there is nothing else that I can think of that should be tested?

@jasonvarga Do you have any input on what else should be tested?

Also, not sure if it would be needed or not, but for the sake of testing I also opted to setup the `constructEnv` function
```php
    protected function constructEnv()
    {
        $filteredEnv = array_merge([
            'HOME',
            'LARAVEL_SAIL',
        ], config('statamic.system.system_environment_variables', []));

        $this->env = collect(getenv())
            ->only($filteredEnv)
            ->toArray();

        if ($this->isRunningInSail() && ! isset($this->env['HOME'])) {
            $this->env['HOME'] = '/home/sail';
        }
    }
```

With the ability to push more keys onto the `collect()->only()` call.

Something like 
```php
    /*
    |--------------------------------------------------------------------------
    | System Environment Variables
    |--------------------------------------------------------------------------
    |
    | Sometimes external processes `Composer` require additional environment variables.
    | Here you can add any variables from getenv() that you would like to pass from Statamic.
    | Simply specifiy the environment variable by name, example: 'HOME' will return the value of getenv('HOME')
    |
    | HOME and LARAVEL_SAIL will automatically attempt to be passed to the process.
    */
    'system_environment_variables' => [
        // 'HOME',
        // 'COMPOSER_HOME',
        // 'COMPOSER_AUTH',
    ],
``` 
In `config/statamic/system.php`

**Comment by michaelr0** [comment]
In addition to the above, if it is a good idea to have
```php
    'system_environment_variables' => [
     //
    ],
```

Then should I also bother with making it possible to specify the value for a particular env variable?
```php
    'system_environment_variables' => [
        'COMPOSER_AUTH',
        'FOO' => 'BAR',
        'BAR' => env('APP_NAME', 'FOO'),
        'RAND' => rand(0, 10),
    ],
```

**Comment by joseph-d** [comment]
Hi @michaelr0 

I just tested downgrading as it seems to work fine too. I went from 3.1.29 to 3.1.28 and then 3.1.27. After that I upgraded back to 3.1.29 again. I re-pasted your new code in each time.

Feels really great to be able to upgrade so effortlessly after such a long time having to use the CLI! Thanks again for taking the time with this!

**Comment by michaelr0** [comment]
@joseph-d Not a problem, happy to help, hopefully this sorts the issue out for good :)

**Comment by jasonvarga** [comment]
Fixed for next release. #4027
