### ISSUE TITLE
Browser notification when changing sites [multi-site]

### ISSUE THREAD

**Issue by zehfred** [statamic/cms#4958]
### Bug description

Clicking through sites show the following browser notification:

"Are you sure? Unsaved changes will be lost."

This happens wether or not there have been any changes to the CP fields.

### How to reproduce

In the sidebar:

Click "Site 1" and do nothing. Click on "Site 2" and do nothing. Changing sites throws that notification.

### Versions

Statamic 3.2.27 Pro
Laravel 8.76.2
PHP 8.1.1

### Installation

Fresh statamic/statamic site via CLI

**Comment by jasonvarga** [comment]
Can you provide your blueprint?

```
php please support:zip-blueprint collection.{collectionhandle}.{blueprinthandle}
```

**Comment by zehfred** [comment]
This happens even with a simple Pages collection.
Occurs on Safari, Brave and Chrome. Haven't tested on Firefox though.

[pages-blueprint.zip](https://github.com/statamic/cms/files/7764728/pages-blueprint.zip)

**Comment by zehfred** [comment]
Don't know if it's relevant but I'm using Valet on my local machine.

**Comment by jasonvarga** [comment]
Actually I'm seeing this on my test site just when refreshing an entry on a single-site site.

**Comment by j3ll3yfi5h** [comment]
Seems related to: #4685

**Comment by arthurperton** [comment]
@zehfred and @jasonvarga I wasn't able to reproduce the issues you're describing, but I just fixed the related issue #4685  – a bug in the slug field dirty state – in PR #4977 and this might very well solve your cases too.

**Comment by zehfred** [comment]
I recorded a video to show you what's going on:

https://www.loom.com/share/0aa19a10cee84a119cc113ff8c1bc943

As you can see, there is no interaction in fields and it still shows the warning dialog.

**Comment by arthurperton** [comment]
Well that’s looking hopeful @zehfred. I see you have different slugs for each site in your entry (aveiro, aveiro-4, aveiro-5, …). That triggers the bug that PR #4977 fixes.

**Comment by adevade** [comment]
> Statamic 3.2.31 Pro
> Laravel 8.79.0
> PHP 8.0.8
> No addons installed

Can confirm that this bug is still present in the latest version. Switching between sites causes the dialog to popup.

I am also using different slugs for each language.

**Comment by jasonvarga** [comment]
#5013 was supposed to fix this, but apparently it's still happening in some situations. I think it's certain fieldtypes that may be triggering it.

If it's happening for you, could you please provide your blueprint using `php please support:zip-blueprint collections.{collectionhandle}.{blueprinthandle}`?

**Comment by j3ll3yfi5h** [comment]
@jasonvarga here it is:
[pages-blueprint.zip](https://github.com/statamic/cms/files/7945742/pages-blueprint.zip)

**Comment by adevade** [comment]
@jasonvarga I made a repo from a fresh install that clearly shows the bug: [adevade/statamic-unsaved-changes-bug](https://github.com/adevade/statamic-unsaved-changes-bug)

See the commits to see what was done.
Follow the instructions in the README.md.

Cheers!
