### ISSUE TITLE
'Hidden' data in a revealer is not saved unless open all revealers (Since version 3.3.7)

### ISSUE THREAD

**Issue by pitcher-maarten** [statamic/cms#5873]
### Bug description

I've discovered that since version 3.3.7 entries are missing data while saving them. After a deeper dive I do think I found the issue when saving an entry. I'm using revealers for hiding some basic options for fieldsets and when they are closed they are not being saved in the entry.md file.

If I keep all revealers open and save the page all is working as aspected.

### How to reproduce

1. Create new blueprint
2. Add fields
3. Add revealer with toggle, buttongroups, ...
4. Save page (while revealers are closed)

### Versions

3.3.7

### Installation

Fresh statamic/statamic site via CLI

### Additional details

![Schermafbeelding 2022-04-20 om 21 41 24](https://user-images.githubusercontent.com/77880620/164310029-52d6d8eb-86a2-47f7-9d9a-504ad5d6c6ba.png)

**Comment by jasonvarga** [comment]
What version did you upgrade _from_ ?

**Comment by pitcher-maarten** [comment]
3.3.6 (which is working as expected)

**Comment by jesseleite** [comment]
@pitcher-maarten Should be fixed in 3.3.9 now!

**Comment by pitcher-maarten** [comment]
@jesseleite I'm still having issues in version `3.3.9` / `3.3.10` while saving these pages. Have already tried both versions and cleared caching etc etc.

**Comment by jesseleite** [comment]
@pitcher-maarten Can you share a screencast maybe, showing your version, as well as the problem when saving fields hidden by a revealer? If you'd rather not share site details publicly, we can also move this to email. https://statamic.com/support

**Comment by jesseleite** [comment]
^ Oh there it is! @pitcher-maarten, We figured out from your video this only happens when sets are set to collapsed by default in the replicator config; Thank you for sending that, good find!

**Comment by jesseleite** [comment]
@pitcher-maarten Should be fixed in 3.3.11 👍
