### ISSUE TITLE
Runtime Parser: Inconsistent variables with Static Site Generation 

### ISSUE THREAD

**Issue by o1y** [statamic/cms#7366]
### Bug description

When building a static site using the `statamic/ssg` package in combination with `runtime` parser, the state of the variables can change randomly during static site generation, resulting in an inconsistent static build. This issue appears to be related to template partials, as demonstrated in the following reproduction.

### How to reproduce

1. Define a variable in your template, e.g in a Blog post Template: `{{ _heading = "{Blogpost: {title}}" }}`
2. Create a generic template partial which outputs the variable, e.g. `<h1>{{ _heading ?? title }}</h1>`
3. Use the template partial in your `Blog` template and in your `Page` template.

**Result in Browser**
* The regular page rendering in the browser is always correct.
* Blogposts returning `Blogpost: This is a Blogpost` and Pages returning just the defined page title.

**Result after `php please ssg:generate`**

When generating a static build with`php please ssg:generate` you will randomly see the Blogpost prefixed headline in generated pages, e.g. `Blogpost: This is a Page`.

_If you can't replicate that, run the generator again a few times since this is a random behaviour._

### Reproduction repo
https://github.com/o1y/statamic-runtime-variable-inconsistency

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.47.0
PHP Version: 8.2.0
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.64 PRO

Statamic Addons
statamic/ssg: 1.2.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

runtime (new)

**Comment by jasonvarga** [comment]
I'm going to guess this is also solved by https://github.com/statamic/cms/pull/7361

I haven't tested it yet, though.

**Comment by o1y** [comment]
@jasonvarga No, tested it :)

**Comment by o1y** [comment]
Hey @JohnathonKoster,

I apologize, but the issue seems to be not completely resolved 😅 I updated my reproduction repository with another case where ssg is using data from previous assignments. When you check the generated entries from the `pages` collection, you'll see that the output from the included partial `{{ partial src="components/breadcrumb" }}` is changing randomly. Can you reproduce that?

_Updated repo:_ https://github.com/o1y/statamic-runtime-variable-inconsistency

Thanks :)

**Comment by JohnathonKoster** [comment]
> 



> Hey @JohnathonKoster,
> 
> I apologize, but the issue seems to be not completely resolved 😅 I updated my reproduction repository with another case where ssg is using data from previous assignments. When you check the generated entries from the `pages` collection, you'll see that the output from the included partial `{{ partial src="components/breadcrumb" }}` is changing randomly. Can you reproduce that?
> 
> _Updated repo:_ https://github.com/o1y/statamic-runtime-variable-inconsistency
> 
> Thanks :)

Will take a look this weekend :)
