### ISSUE TITLE
Addons page does not list addons with minimum Statamic version of 4.0

### ISSUE THREAD

**Issue by jacksleight** [statamic/cms#8166]
### Bug description

I mentioned something related to this in a support ticket but I've had some time to look at it properly now.

The addons page in the CP (both All and Installed tabs) is not listing any addons with a minimum Statamic version of 4.0. However the installed tab at the top does show the correct number of installed addons.

This seems to be because of this line in `AddonsQuery`:

```php
'filter' => ['statamic' => 3],
```

Changing that to 4 makes them appear, however then any addons with a minimum version of 3.x (that also support 4.0) disappear instead.

### How to reproduce

- Try to search for or install an addon with a minimum Statamic version of 4.0, eg. Runway or Bard Texstyle.
- Change the filter value to 4 and then try to search for or install an addon with a minimum Statamic version of 3.x (that also supports 4.0), eg. Bard Mutator.

### Environment

```yaml
Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.1.3 Solo
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

None

**Comment by robdekort** [comment]
https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif

**Comment by robdekort** [comment]
![giphy](https://github.com/statamic/cms/assets/69107412/6bfbc850-b40b-4de2-a000-5fb5d62fdbe9)

My Addons CP page is very sad indeed.

**Comment by robdekort** [comment]
I could totally live without this page altogether btw. You need composer anyways to install addons.

**Comment by joshuaDclark** [comment]
[](url)Reaching out on what may be a similar issue. The Updates page in CP does not show the updated version of addon packages even after they were updated. 

Confirmed packages were updated based on changes in the updates. 

Uploading a screenshot for reference. Could this possibly be a Statamic UI issue?

![updates](https://github.com/statamic/cms/assets/31425297/e57c04d1-e815-461b-b4b8-91e6fccc3f21)

**Comment by jasonvarga** [comment]
@joshuaDclark Can you post the output of this command?

```
composer show -D | grep peak
```

**Comment by joshuaDclark** [comment]
> @joshuaDclark Can you post the output of this command?
> 
> ```
> composer show -D | grep peak
> ```

@jasonvarga 

`studio1902/statamic-peak-browser-appearance v3.2    
studio1902/statamic-peak-commands           v2.3.3  
studio1902/statamic-peak-seo                v6.0    
studio1902/statamic-peak-tools              v3.2   `

**Comment by jasonvarga** [comment]
@joshuaDclark I've updated something on statamic.com for that. Try clearing your cache then running `php please addons:discover`.

**Comment by joshuaDclark** [comment]
@jasonvarga Thanks. I tried this and now I can see what is up to date in CP. However it appears it unlisted some of the PEAK addons. I'm also still seeing a notification flag to the left of the Updates tab in the left hand column within CP indicating that there are 3 updates available.

**Comment by jasonvarga** [comment]
Screenshot?

**Comment by joshuaDclark** [comment]
> 
![updates_2](https://github.com/statamic/cms/assets/31425297/432a968c-28e9-490b-8e3f-c0f75d7ea49d)

**Comment by jasonvarga** [comment]
Those should be fixed now. It was an issue with some data on the statamic.com side.

(@robdekort The "Minimum Git Version" for those were set to `v1.0` - changing to `1` fixed it. We'll improve validation there.)

**Comment by robdekort** [comment]
Thanks Jason, I’ll look into that!

**Comment by robdekort** [comment]
Hey Jason. I see you changed all them for my addons. Thanks. But the initial issue still seems open. They're not listed in the addons tab, and you also can't search for v4+ addons.

**Comment by robdekort** [comment]
Yup. All good now!
