### ISSUE TITLE
Slug sometimes updates after an entry is already published. 

### ISSUE THREAD

**Issue by ncristovao** [statamic/cms#9206]
### Bug description

Current Behavior:

1. Sometimes, after an entry is published, if you update the title (or whatever field the slug is based on), the slug will also update. This causes the previous page to 404 and causes a new URL to be generated. 
2. When creating an entry and saving (but not published), the slug is set. However, if you change the field the slug is based on before publishing, then the slug does not get updated, when it should since the entry is not live.

Expected behavior:

1. The slug should always update to the set field before an entry is published.
4. After the entry has been published, the slug should not update, unless the user clicks the regenerate button.

### How to reproduce

Unfortunately, I can't always re-produce the first error, but the second one happens every time. Save an entry. Reload. Update the title and the slug does not get updated.

### Environment

```yaml
Environment
Laravel Version: 10.28.0
PHP Version: 8.2.8
Composer Version: 2.6.6
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: sync
Session: database

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.39.0 PRO

Statamic Addons
statamic/eloquent-driver: 2.0.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

Runtime (default)

**Comment by duncanmcclean** [comment]
Are you using revisions at all?

**Comment by duncanmcclean** [comment]
Can you try updating to [v4.42.0](https://github.com/statamic/cms/releases/tag/v4.42.0) and let me know if you're still experiencing the same issues?

**Comment by ncristovao** [comment]
I haven't updated yet, but I'm currently on 4.41 and was just able to see the issue again. These were the steps I took.

- An entry was created and saved, but not published.
- Hours later and on a different computer, the entry was reopened, the title was changed and the issue was saved and published. 
- Without reloading the page, if I tried to update the title again, it was changing the slug as well.
- After reloading the page, updating the title no longer updated the slug.

**Comment by duncanmcclean** [comment]
I'm going to assume this was fixed in v4.42.0 (as it fixed some other related issues). If you're having issues after updating, leave a comment and we can re-open.

**Comment by ncristovao** [comment]
I can confirm this is still happening. Here is how you can reproduce it.

1) Enable revisions
2) Create an entry, save it and publish it.
3) Attempt to change the title without refreshing the page, it will also result in the slug being updated

**Comment by jasonvarga** [comment]
> Attempt to change the title without refreshing the page

What does this mean? You typed in the title field and then what?

**Comment by ncristovao** [comment]
I mean, that if I decide to update the title field (which the slug is based on) right after publishing, the it updates the slug as well, when it shouldn't since the article has already been published.

If I do to another CP page and then go back to the article and update the title, then the slug does not get updated, which is correct.
