### ISSUE TITLE
Creating Translation on existing post does not work

### ISSUE THREAD

**Issue by matrad** [statamic/cms#964]
Steps to reproduce:

1. Install statamic beta
2. Transform the Multisite migration with the `please multisite` command
*sites.php content:*
```
    'sites' => [

        'de' => [
            'name' => 'de',
            'locale' => 'de_DE',
            'url' => '/',
        ],
        'it' => [
            'name' => 'it',
            'locale' => 'it_IT',
            'url' => '/it/',
        ]

    ]
```
3. Create a new site in the page-collection
4. Klick on the right on the "Pages" it collection, it happens nothing and I see this issue in the debugbar (screen)

`
![image](https://user-images.githubusercontent.com/660903/69496240-57f6cd00-0ed0-11ea-88d2-06d4d06108ef.png)

When debugging the API, then the
`Taxonomy::findByHandle($this->childKey())` is probably = null, where the `$this->childKey()` has the value `"cp"`

The Request where this exception is raised:
`curl 'http://127.0.0.1:8000/cp/structures/pages/entries/c2154258-149a-4678-b208-693f5d4fd613/mieten/localize' ...  -H 'Referer: http://127.0.0.1:8000/cp/structures/pages/entries/c2154258-149a-4678-b208-693f5d4fd613/mieten' --data-binary '{"site":"it"}' --compressed`

**Comment by matrad** [comment]
@jackmcdade fyi this is a bug what prevents me testing the multilanguage-features in v3, so it'd be great if you can prioritize that 😁

**Comment by patrickhoehn** [comment]
Similar issue here! If I click on a non active site on the right, the dot stays red and the loading wheel keeps spinning with this error in the debugger: `Call to a member function collections() on null {"userId":"9468beda-b2b9-4e16-9f7f-10e2f55957f2","exception":{}}`

<img width="301" alt="Bildschirmfoto 2019-12-01 um 20 40 08" src="https://user-images.githubusercontent.com/17851700/69919251-3d49c880-147b-11ea-8a52-fdb24f77a3b2.png">

**Comment by matrad** [comment]
Now since the latest release the exception changed to:

```
Call to a member function routeData() on null
.../vendor/statamic/cms/src/Structures/Page.php#294
Symfony\Component\Debug\Exception\FatalThrowableError

    public function routeData()
    {
        return $this->entry()->routeData();
    }

    public function blueprint()
```

**Comment by matrad** [comment]
On the current Release the exception is
Line 47 in `vendor/statamic/cms/src/Http/Controllers/FrontendController.php`
`        throw new NotFoundHttpException;`

**Comment by matrad** [comment]
After debugging this issue the issue is in the `PublishForm.vue`.

Here on Line 521 we've this code:
```
        createLocalization(localization) {
            const url = this.activeLocalization.url + '/localize';
            this.$axios.post(url, { site: localization.handle }).then(response => {
                this.editLocalization(response.data);
            });
        },
```

The Problem is, that the this.activeLocalization.url contains a value with `/cp/structures/pages/entries/`, so the call to the localization-endpoint would be `http://127.0.0.1:8000/cp/structures/pages/entries/4dfb27a3-b415-4ef6-a7d0-bed80707c6f6/impressum/localize`.

In the `routes/cp.php` the Endpoint `POST /localize` is defined under `collection`, not `structures`.
Executing the same POST-Request in the Terminal, by using this url `http://127.0.0.1:8000/cp/collection/pages/entries/4dfb27a3-b415-4ef6-a7d0-bed80707c6f6/impressum/localize` it works, and also creates the exception.

**Comment by jasonvarga** [comment]
Should be solved in the next release with all the structure-related changes. Please re-open if not.

**Comment by patrickhoehn** [comment]
@jasonvarga for me this issue persists in beta 20. Set all up for multi-site and for the primary site everything is fine with collections and entries but once I hit the button for the translation the wheel keeps spinning, refreshing throws an error: `LOG.error: Undefined offset: 0 {"userId":"9bb4feff-7955-4eec-8f34-b5892a58a174","exception":{}}`. 

<img width="294" alt="translation" src="https://user-images.githubusercontent.com/17851700/77534785-95c52b80-6e99-11ea-82a3-7f44633d8bae.png">

A new file is created in the translated folder like `2020-03-25-1147.home.md` with this content `
updated_at: 1585137495
updated_by: 9bb4feff-7955-4eec-8f34-b5892a58a174
id: 761684f0-41bf-4b92-9223-5d6b99050703
origin: 3c2dc69e-6bfb-4c53-b71c-97995da5d1f6
published: false
`
